spring:
  datasource:
    url: jdbc:mysql://localhost:3306/inventory_service
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  flyway:
    baseline-on-migrate: true
    baseline-description: "init"
    baseline-version: 0
    enabled: true
    user: root
    password:
  jpa:
    hibernate:
      ddl-auto: update