spring:
  datasource:
    url: jdbc:mysql://${INVENTORY_MYSQL:localhost}:${INVENTORY_MYSQL_PORT:3308}/inventory-service
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  flyway:
    baseline-on-migrate: true
    baseline-description: "init"
    baseline-version: 0
    enabled: true
    user: root
    password: root
    url: jdbc:mysql://${INVENTORY_MYSQL:localhost}:${INVENTORY_MYSQL_PORT:3308}/inventory-service
  jpa:
    hibernate:
      ddl-auto: update
resilience4j:
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowType: COUNT_BASED
      slidingWindowSize: 10
      failureRateThreshold: 50
      waitDurationInOpenState: 5s
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
  instances:
    inventory-service:
      baseConfig: default
  timelimiter:
    configs:
      default:
        timeout-duration: 3s