spring:
  datasource:
    url: jdbc:mysql://localhost:3306/4twin_semestre1
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY:eyJhbGciOiJIUzI1NiJ9eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTcyNzQzOTg5NiwiaWF0IjoxNzI3NDM5ODk2fQw8WJR8e2efdua9k3CTMDkijVuLoTdMSgHRM3DleeiPo}
      expiration: 864000
  mailing:
    frontend:
      activation_url: http://${FRONTEND_ACTIVATION_URL_HOST:localhost}:${FRONTEND_ACTIVATION_URL_PORT:80}/activate-account
  datasource.hikari:
    connection-timeout: 20000
logging:
  level:
    root: DEBUG
    com.fasterxml.jackson: DEBUG
    org.springframework.security: DEBUG