spring:
  cloud:
    kubernetes:
      discovery:
        enabled: true
        all-namespaces: false

  datasource:
    url: jdbc:mysql://${Mailer_MYSQL:localhost}:${MAILER_MYSQL_PORT:3307}/mailer-service
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY:eyJhbGciOiJIUzI1NiJ9eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTcyNzQzOTg5NiwiaWF0IjoxNzI3NDM5ODk2fQw8WJR8e2efdua9k3CTMDkijVuLoTdMSgHRM3DleeiPo}
      expiration: 864000
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 60000
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 1000
          multiplier: 2.0
          max-interval: 10000
  mail:
    queue: mailer-queue
    exchange: mailer-exchange
    routing-key: mailer-routing-key
application:
  mailing:
    frontend:
      activation_url: http://${FRONTEND_ACTIVATION_URL_HOST:localhost}:${FRONTEND_ACTIVATION_URL_PORT:80}/activate-account
  datasource.hikari:
    connection-timeout: 20000
  flyway:
    baseline-on-migrate: true
    baseline-description: "init"
    baseline-version: 0
    enabled: true
    user: root
    password: root
    url: jdbc:mysql://${Mailer_MYSQL:localhost}:${MAILER_MYSQL_PORT:3307}/mailer-service
logging:
  level:
    root: DEBUG
    com.fasterxml.jackson: DEBUG
    org.springframework.security: DEBUG