spring:
  profiles:
    active: native
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/order_service
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    baseline-on-migrate: true
    baseline-description: "init"
    baseline-version: 0
    enabled: true
    user: root
    password:
server:
  port: 8082
  servlet:
    context-path: /api/v1