spring:
  cloud:
    kubernetes:
      discovery:
        enabled: true
        all-namespaces: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${ORDER_MYSQL:localhost}:${ORDER_MYSQL_PORT:3309}/order-service
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    url: jdbc:mysql://${ORDER_MYSQL:localhost}:${ORDER_MYSQL_PORT:3309}/order-service
    baseline-on-migrate: true
    baseline-description: "init"
    baseline-version: 0
    enabled: true
    user: root
    password: root
server:
  port: 8082
  servlet:
    context-path: /api/v1
resilience4j:
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowType: COUNT_BASED
      slidingWindowSize: 10
      failureRateThreshold: 50
      waitDurationInOpenState: 5s
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
  instances:
    inventory-service:
      baseConfig: default
  timelimiter:
    configs:
      default:
        timeout-duration: 3s