spring:
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      host: localhost
      port: 27017
      database: product-service
    redis:
      host: localhost
      port: 6379
  elasticsearch:
    uris: http://localhost:9200
    username: elastic
    password: 786919
    connection-timeout: 5000
resilience4j:
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowType: COUNT_BASED
      slidingWindowSize: 10
      failureRateThreshold: 50
      waitDurationInOpenState: 5s
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
  instances:
    product-service:
      baseConfig: default
  timelimiter:
    configs:
      default:
        timeout-duration: 3s

