spring:
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      host: ${PRODUCT_MONGO:localhost}
      port: 27017
      database: product-service
      username: admin
      password: admin
      authentication-database: admin
    redis:
      host: ${PRODUCT_REDIS:localhost}
      port: 6379
  elasticsearch:
    uris: ${PRODUCT_ELASTIC:http://localhost:9200}
    #username: elastic
    #password: elastic
    connection-timeout: 60000
    socket-timeout: 60000
resilience4j:
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowType: COUNT_BASED
      slidingWindowSize: 10
      failureRateThreshold: 50
      waitDurationInOpenState: 5s
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
  instances:
    product-service:
      baseConfig: default
  timelimiter:
    configs:
      default:
        timeout-duration: 3s
