spring:
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/4twin_semestre1
    username: root
    password:
    hikari:
      connection-timeout: 20000
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY:eyJhbGciOiJIUzI1NiJ9eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTcyNzQzOTg5NiwiaWF0IjoxNzI3NDM5ODk2fQw8WJR8e2efdua9k3CTMDkijVuLoTdMSgHRM3DleeiPo}
      Expiration: 864000
  mailing:
    frontend:
      activation_url: http://${FRONTEND_ACTIVATION_URL_HOST:localhost}:${FRONTEND_ACTIVATION_URL_PORT:80}/activate-account
    backend:
      mailer: http://${BACKEND_MAILER_URL_HOST:localhost}:${BACKEND_MAILER_URL_PORT:8082}/api/v1/mailer/sendmail

server:
  servlet:
    context-path: /api/v1
  port: 8084

