spring:
  application:
    name: product-service
  config:
    import: optional:configserver:http://${CONFIG_SERVER_HOST:localhost}:8888
server:
  port: 8082
  servlet:
    context-path: /api/v1
logging:
  file:
    name: /var/log/product-service.log
