spring:
  application:
    name: product-service
  config:
    import: optional:configserver:http://localhost:8888
server:
  port: 8081
  servlet:
    context-path: /api/v1
logging:
  file:
    name: C:\xampp\htdocs\ElasticStack-Redis-Spring-Project\config-service\logs\elk-stack-user-service.log
