spring:
  application:
    name: inventory-service
  datasource:
      url: jdbc:mysql://localhost:3306/inventory_service
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password:
  config:
    import: optional:configserver:http://localhost:8888
server:
  port: 8083
  servlet:
    context-path: /api/v1