  spring:
    application:
      name: inventory-service
    config:
      import: optional:configserver:http://${CONFIG_SERVER_HOST:localhost}:8888
  server:
    port: 8083
    servlet:
      context-path: /api/v1