services:
  frontend:
    build: ./Angular-Spring-Frontend
    ports:
      - "4200:4200"
    volumes:
      - ./angular-app:/app
      - /app/node_modules

  spring: 
    build: ./Angular-Spring-Backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/4twin_semestre1
      # Add other environment variables as needed

  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=786919
      - MYSQL_DATABASE=4twin_semestre1

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./angular-app/dist:/usr/share/nginx/html
    depends_on:
      - frontend
      - spring