spring:
  profiles:
    active: native
  application:
    name: config-server
  cloud:
    discovery:
      enabled: true
    config:
      server:
        native:
          search-locations: classpath:/configurations
eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVICE:http://localhost:8761/eureka/}
  instance:
    preferIpAddress: true
server:
  port: 8888
