spring:
  config:
    activate:
      on-profile: docker
  application:
    name: config-server
  cloud:
    discovery:
      enabled: true
    config:
      server:
        native:
          search-locations: classpath:/configurations
  lifecycle:
    timeout-per-shutdown-phase: 10s
server:
  port: 80
  shutdown: graceful
management:
  endpoint:
    health:
      probes:
        enabled: true
    group:
      readiness:
        include: readinessState
